services:
  - type: web
    name: raizes-urbanas
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_TOKEN
        sync: false
    disk:
      name: cadastros
      mountPath: /opt/render/project/src/data
      sizeGB: 1
